# Change these first
owner: james-martinez # Your GitHub organization or username, where this repository lives
repo: dso # The name of this repository

sites:
  - name: Login
    url: https://login.dso.mil
  - name: Repo1
    url: https://repo1.dso.mil
  - name: Ironbank
    url: https://ironbank.dso.mil
  - name: Registry1
    url: https://registry1.dso.mil
  - name: Portal
    url: https://portal.cnap.dso.mil
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /dso
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: dso Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page of services from dso
  navbar:
    - title: Status
      href: https://$OWNER.github.io/$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
